services:
  url-frontend:
    build: ./frontend
    container_name: url-frontend
    restart: always
    expose:
      - "3000"
    env_file:
      - ./frontend/.env.production
    networks:
      - shared

  url-backend:
    build: ./backend
    container_name: url-backend
    restart: always
    expose:
      - "8000"
    env_file:
      - ./backend/.env.prod
    networks:
      - shared

networks:
  shared:
    external: true
